spring:
  application:
    name: board_api1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/vgdb
#    url: jdbc:mariadb://10.10.10.54:13306/vgdb
    username: vgdbuser
    password: vgdbuser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: ${org.sunbong.upload.path}  # 업로드 경로를 org.sunbong.upload.path와 연동

org:
  sunbong:
    accessTime: 1
    refreshTime: 10
    alwaysNew: true
    upload:
      path: C:/upload

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
